### ISSUE TITLE
HTTP协议返回格式错误 

### ISSUE THREAD

**Issue by Me7426** [ifyour/ipac#18]
实测应为`PROXY 123.123.123.123`才能生效,`HTTP 123.213.123.123`格式无效

**Comment by ifyour** [comment]
[根据文档](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_(PAC)_file)，这个是没问题的。

![image](https://user-images.githubusercontent.com/15377484/82568883-0c3c8c00-9bb2-11ea-88db-fa5e3eea7708.png)

我测了一下，只保留 HTTP 可以的。😂

**Comment by Me7426** [comment]
我把firefox和chrome都试了一遍,
`HTTP`开头两个浏览器都不生效
`PROXY`和`HTTPS`两个浏览器都生效.
估计是为了安全忽略了http吧.
