### ISSUE TITLE
Don't know how to work with switch profile. Need help!

### ISSUE THREAD

**Issue by Gabirel** [ifyour/ipac#41]
Hi, thanks for your wonderful works.

I am able to make it work according to your instructions. (i.e., Set it as pac file).

But, currently, I need more of that. But I can't figure it out how to make it right. I am not sure whether it is a bug or simply my unknown mistake.

This screenshot below shows how I configure this with a switch profile: 
![image](https://user-images.githubusercontent.com/12933851/88629946-7b6abb00-d0e2-11ea-8366-2df0e48481cf.png)

Explanation:
- `Force-connect` enables me to the proxy network via a socks5.
- `Direct` means no proxy if domain matches in the list of `ipac`.

But, I got this result from Baidu. It says my IP is still the proxy network. Why? I don't understand how it works for the whitelist.
![image](https://user-images.githubusercontent.com/12933851/88630322-fdf37a80-d0e2-11ea-8a79-377e52eddb5b.png)

So, How can I make it work well for me with this switch profile? Thanks in advance.

**Comment by ifyour** [comment]
Thank you for your feedback on the usage. For a better experience, I recommend the following configuration.

Dropbox Link: [OmegaOptions.bak](https://www.dropbox.com/s/ga9dy75pqmptc9z/OmegaOptions.bak?dl=0)

You can save your current configuration and then import my configuration to see how it's used.

**Comment by Gabirel** [comment]
I tried your configuration but it doesn't work either.

Here're some screenshots:
1. It works for Chinese website.
![image](https://user-images.githubusercontent.com/12933851/88744711-b9b3b900-d17a-11ea-98ef-2f14dd0c50f5.png)

2. It does not have a network access at all if I use your configuration.
![image](https://user-images.githubusercontent.com/12933851/88744718-c0423080-d17a-11ea-9b96-f4fbd2bf7692.png)

-------
PS: 
1. I am pretty sure I imported your configuration correctly.

2. My proxied network is fine too. No glitch at all.

**Comment by ifyour** [comment]
Make sure you have the correct Socks5 proxy port, in the above configuration file I use the port number 1080.

**Comment by Gabirel** [comment]
> Make sure you have the correct Socks5 proxy port, in the above configuration file I use the port number `1080`.

I can 100% sure that proxied profile works since I tried that under that profile.

**Comment by ifyour** [comment]
That's odd, mine works fine! 😂

**Comment by Gabirel** [comment]
> Are you using Chrome?

Yes. Chrome 84.0.4147.89 (Official Build) (64-bit) on macOS 10.15.6

**Comment by ifyour** [comment]
Change your Socks5 port number to 1080.

Or use this address: `https://ipac.now.sh/?s=YOUR_PROT_NUMBER`

I forgot about this! 😭

**Comment by Gabirel** [comment]
It works! Thanks.
I have my settings like this: `https://ipac.now.sh/?s=10808&h=1087`
But I have two questions:
1. Why do I need to assign a socket port and HTTP port to this pac? Can you explain to me about this? I don't see it necessary though. I hope I could learn more details about it.

2. What does it happen if I set up my configuration like my first attempt? (See the picture below)
![image](https://user-images.githubusercontent.com/12933851/88748074-b9b7b700-d182-11ea-9541-097cb3e5d617.png)

**PS:**  I tried this scheme. It works for me though. And I believe this is the most intuitive way to set up. So, my question is what is the difference between your configuration and my intuitive setup?

**Comment by ifyour** [comment]
> Why do I need to assign a socket port and HTTP port to this pac? 

Everyone's configuration is different and is set up this way to increase flexibility. HTTP is used as an alternative and the HTTP proxy is used when SOCKS5 does not work.

> What does it happen if I set up my configuration like my first attempt?

As far as I know, the blacklist is set up here.

**Comment by Gabirel** [comment]
I see. I would prefer your way to use the whitelist although my intuitive setup works as well.

Thanks again for your quick response and explanation. 👍
