### ISSUE TITLE
关于ipv6

### ISSUE THREAD

**Issue by DragonLie** [ifyour/ipac#7]
大佬可以完善一下脚本嘛？
我这边属于IPv4和v6公用的情况，可以将https://www.test-ipv6.com/ 添加进pac里面么？
然后我想问一下，可以增加ipv6的判别嘛
在你的文件里我只看到了关于IPv4的判别~~
  if (checkIpv4(host) === true) {
    setCache(host, direct);
    return getProxyFromDirectIP(host);
  }

**Comment by ifyour** [comment]
OK, 感谢反馈。

我研究下，主要是我也没有 IPv6 环境测试。可以考虑来个 PR 吗？

**Comment by DragonLie** [comment]
哈哈 没听懂 啥叫PR呀 /xk

**Comment by ifyour** [comment]
Pull requests
就是贡献代码的意思， Fork 一份，然后在你的分支贡献代码。😄发起 PR 我合并到 master。

**Comment by DragonLie** [comment]
好滴，那我试试康



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Willard Wong"<notifications@github.com&gt;; 
发送时间: 2020年4月26日(星期天) 下午2:11
收件人: "ifyour/ipac"<ipac@noreply.github.com&gt;; 
抄送: "ī"<310856638@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ifyour/ipac] 关于ipv6 (#7)





 
Pull requests
 就是贡献代码的意思， Fork 一份，然后在你的分支贡献代码。😄发起 PR 我合并到 master。
 
&mdash;

**Comment by ifyour** [comment]
Cool，你真棒 😎
